"use client";
import { ContactShadows, Html, OrbitControls } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { useEffect, useMemo, useRef } from "react";
import { CatmullRomCurve3, MathUtils, PerspectiveCamera, Vector3 } from "three";
import type { Group } from "three";
import type { OrbitControls as OrbitControlsImpl } from "three-stdlib";
import type { RadiatorMount, Visual3DPart, Visual3DScene } from "@/lib/visual-3d";
import type { VisualCategory } from "@/lib/visual-build";

const accents = { empty: "#315543", installed: "#000000", next: "#dfb85e", warning: "#e3a83c", conflict: "#e05a48" } as const;
function Material({ part, active, color = part.profile.primaryColor, metalness = part.profile.metalness, roughness = part.profile.roughness }: { part: Visual3DPart; active: boolean; color?: string; metalness?: number; roughness?: number }) {
 const ghost = part.state === "empty" || part.state === "next"; const accent = active ? "#dfb85e" : accents[part.state];
 return <meshStandardMaterial color={color} metalness={metalness} roughness={roughness} transparent={ghost} opacity={ghost ? .2 : 1} wireframe={part.state === "empty"} emissive={accent} emissiveIntensity={active ? .28 : part.state === "installed" ? .015 : .14}/>;
}
function Interactive({ part, children, onSelect, onHover }: { part: Visual3DPart; children: React.ReactNode; onSelect: (p: Visual3DPart) => void; onHover: (p?: Visual3DPart) => void }) {
 return <group position={part.position} onClick={e=>{e.stopPropagation();onSelect(part)}} onPointerOver={e=>{e.stopPropagation();document.body.style.cursor="pointer";onHover(part)}} onPointerOut={()=>{document.body.style.cursor="";onHover()}}>{children}</group>;
}
function Fan({ part, active, radius=.32 }: {part:Visual3DPart;active:boolean;radius?:number}) { return <group><mesh rotation={[0,Math.PI/2,0]}><cylinderGeometry args={[radius,radius,.1,24]}/><Material part={part} active={active} color="#202622"/></mesh><mesh rotation={[0,Math.PI/2,0]} position={[.06,0,0]}><torusGeometry args={[radius*.67,.026,8,24]}/><meshStandardMaterial color="#87928c" metalness={.5} roughness={.45}/></mesh></group>; }
function Tubes({part,active}:{part:Visual3DPart;active:boolean}) { const target=part.connectionTarget!; const start:Vector3TupleLike = radiatorTubeStart(part.mount); const curves=useMemo(()=>[-.1,.1].map(o=>new CatmullRomCurve3([new Vector3(start[0],start[1]+o,start[2]+o),new Vector3((start[0]+target[0])/2+.35,(start[1]+target[1])/2,start[2]),new Vector3(target[0]+.28,target[1]+o,target[2]),new Vector3(target[0]+.18,target[1]+o,target[2])])),[start,target]); return <>{curves.map((curve,i)=><mesh key={i}><tubeGeometry args={[curve,28,.055,9,false]}/><Material part={part} active={active} color="#111714" roughness={.82}/></mesh>)}</>; }
type Vector3TupleLike=[number,number,number];
const radiatorTubeStart=(mount?:RadiatorMount):Vector3TupleLike=>mount==="front"?[0,.55,-.05]:mount==="side"?[-.18,-.55,0]:[-.45,-.05,.15];
function Radiator({part,active}:{part:Visual3DPart;active:boolean}) { const length=1.9*part.scale[0], cross=.62, thick=.24; const vertical=part.mount!=="top"; const rotation:Vector3TupleLike=part.mount==="top"?[0,0,0]:part.mount==="front"?[0,0,Math.PI/2]:[0,0,Math.PI/2]; const fanAxis=length*.82/Math.max(1,part.instances-1); return <group rotation={rotation}><mesh><boxGeometry args={[length,cross,thick]}/><Material part={part} active={active} color="#252c28"/></mesh>{Array.from({length:part.instances},(_,i)=><group key={i} position={[(i-(part.instances-1)/2)*fanAxis,0,thick/2+.04]} rotation={[0,Math.PI/2,0]}><Fan part={part} active={active} radius={.27}/></group>)}{vertical&&<mesh position={[0,0,-.14]}><boxGeometry args={[length*.92,cross*.84,.04]}/><meshStandardMaterial color="#3e4842"/></mesh>}</group>; }
function Component({part,active}:{part:Visual3DPart;active:boolean}) {
 if(part.kind==="motherboard") return <group scale={part.scale}><mesh><boxGeometry args={[.11,2.9,2.45]}/><Material part={part} active={active}/></mesh><mesh position={[.075,.8,-.7]}><boxGeometry args={[.06,.55,.7]}/><Material part={part} active={active} color={part.profile.secondaryColor}/></mesh></group>;
 if(part.kind==="cpu") return <mesh scale={part.scale}><boxGeometry/><Material part={part} active={active} color="#d9dedb" metalness={.92} roughness={.18}/></mesh>;
 if(part.kind==="ram") return <>{Array.from({length:part.instances},(_,i)=><mesh key={i} position={[.16,0,(i-(part.instances-1)/2)*.16]}><boxGeometry args={[.12,1.0,.1]}/><Material part={part} active={active}/></mesh>)}</>;
 if(part.kind==="gpu") { const connectors=part.metadata.hpwr?1:Math.max(1,Math.min(3,Number(part.metadata.conn8||0)+Number(part.metadata.conn6||0))); return <group scale={part.scale}><mesh><boxGeometry args={[.62,.68,2.75]}/><Material part={part} active={active}/></mesh><mesh position={[-.34,-.05,-1.32]}><boxGeometry args={[.08,.62,.12]}/><meshStandardMaterial color="#aeb6b1" metalness={.8}/></mesh><Html position={[.321,0,.18]} rotation={[0,Math.PI/2,0]} transform center distanceFactor={4}><span style={{display:"block",maxWidth:"110px",overflow:"hidden",color:part.profile.accentColor,font:"700 10px IBM Plex Mono, monospace",letterSpacing:".08em",whiteSpace:"nowrap"}}>{part.profile.family||"GPU"}</span></Html>{Array.from({length:connectors},(_,i)=><mesh key={i} position={[0,.37,.75-i*.25]}><boxGeometry args={[.28,.1,.18]}/><meshStandardMaterial color="#090c0a"/></mesh>)}</group>; }
 if(part.kind==="air-cooler") return <group><mesh><boxGeometry args={[.9,1.28,.88]}/><Material part={part} active={active} color="#59625d"/></mesh><group position={[.5,0,0]}><Fan part={part} active={active}/></group></group>;
 if(part.kind==="aio") return <><Radiator part={part} active={active}/><Tubes part={part} active={active}/><group position={part.connectionTarget!.map((v,i)=>v-part.position[i]) as Vector3TupleLike}><mesh rotation={[0,Math.PI/2,0]}><cylinderGeometry args={[.27,.27,.18,24]}/><Material part={part} active={active}/></mesh></group></>;
 if(part.kind==="m2") return <>{Array.from({length:part.instances},(_,i)=><group key={i} position={[.1,-i*.3,i*.16]}><mesh><boxGeometry args={[.1,.22,.82]}/><Material part={part} active={active} color="#244936"/></mesh><mesh position={[.06,0,-.36]}><boxGeometry args={[.02,.2,.09]}/><meshStandardMaterial color="#dfb85e" metalness={.75}/></mesh></group>)}</>;
 if(part.kind==="psu") return <group scale={part.scale}><mesh><boxGeometry args={[1.42,1.12,1.48]}/><Material part={part} active={active}/></mesh><group position={[.76,0,0]}><Fan part={part} active={active} radius={.38}/></group></group>;
 if(part.kind==="fan") return <>{Array.from({length:part.instances},(_,i)=><group key={i} position={[0,(i-(part.instances-1)/2)*.76,0]}><Fan part={part} active={active}/></group>)}</>;
 const sizes:Partial<Record<Visual3DPart["kind"],Vector3TupleLike>>={"drive-25":[.18,1.0,.72],"drive-35":[.28,1.35,1.0],expansion:[.32,.26,1.5],rgb:[.08,3.5,.08]}; return <mesh><boxGeometry args={sizes[part.kind]||[.5,.5,.5]}/><Material part={part} active={active}/></mesh>;
}
function Chassis({scene}:{scene:Visual3DScene}) { const {size}=scene.layout; const [w,h,d]=size; const t=.08; const dual=scene.layout.family==="dual-chamber", airflow=scene.layout.family==="airflow"; return <group><mesh position={[scene.layout.tray[0],0,0]}><boxGeometry args={[t,h*.91,d*.9]}/><meshStandardMaterial color="#26352d" roughness={.64}/></mesh><mesh position={[0,-h/2+t/2,0]}><boxGeometry args={[w,t,d]}/><meshStandardMaterial color="#36413c" metalness={.7}/></mesh><mesh position={[0,h/2-t/2,0]}><boxGeometry args={[w,t,d]}/><meshStandardMaterial color="#36413c" metalness={.7}/></mesh><mesh position={[0,0,-d/2+t/2]}><boxGeometry args={[w,h,t]}/><meshStandardMaterial color="#303a35" metalness={.72}/></mesh><mesh position={[0,0,d/2-t/2]}><boxGeometry args={[w,h,t]}/><meshPhysicalMaterial color={airflow?"#5a7767":"#40544a"} wireframe={airflow} transparent opacity={airflow?.32:.1} roughness={.35} transmission={airflow?0:.45}/></mesh>{dual&&<mesh position={[-w*.23,-h*.29,0]}><boxGeometry args={[w*.42,h*.32,d*.9]}/><meshStandardMaterial color="#1d2822" roughness={.5}/></mesh>}<mesh position={[w/2-t/2,0,0]}><boxGeometry args={[t,h*.94,d*.94]}/><meshPhysicalMaterial color="#7ba18d" transparent opacity={.09} roughness={.12} transmission={.55}/></mesh></group>; }
export default function ForgeScene({scene,active,onSelect,onHover,resetSignal}:{scene:Visual3DScene;active?:VisualCategory;onSelect:(p:Visual3DPart)=>void;onHover:(p?:Visual3DPart)=>void;resetSignal:number}) { const controls=useRef<OrbitControlsImpl>(null), assembly=useRef<Group>(null); const {camera,size,invalidate}=useThree(); const cameraRef=useRef(camera); useEffect(()=>{const fitted=cameraRef.current; if(!(fitted instanceof PerspectiveCamera))return; const [w,h,d]=scene.layout.size; const radius=Math.hypot(w,h,d)/2; const vfov=MathUtils.degToRad(fitted.fov); const hfov=2*Math.atan(Math.tan(vfov/2)*fitted.aspect); const distance=radius/Math.sin(Math.min(vfov,hfov)/2)*1.03; const direction=new Vector3(1,.48,1.18).normalize(); fitted.position.copy(new Vector3(...scene.focusTarget)).addScaledVector(direction,distance); fitted.near=Math.max(.05,distance-radius*1.4); fitted.far=distance+radius*5; fitted.updateProjectionMatrix(); controls.current?.target.set(...scene.focusTarget); controls.current?.update(); invalidate()},[invalidate,resetSignal,scene,size.width,size.height]); return <><ambientLight intensity={1.25} color="#dbe8df"/><hemisphereLight args={["#d9eee4","#21382c",1.75]}/><directionalLight position={[5,7,6]} intensity={2.8} color="#ffe9bd"/><directionalLight position={[-4,2,5]} intensity={1.8} color="#79cbb7"/><pointLight position={[1,1,0]} intensity={2.2} distance={8} color="#a7d3bd"/><group ref={assembly}><Chassis scene={scene}/>{scene.parts.map(part=><Interactive key={part.id} part={part} onSelect={onSelect} onHover={onHover}><Component part={part} active={active===part.category}/></Interactive>)}</group><ContactShadows position={[0,scene.bounds.min[1]-.05,0]} opacity={.36} scale={8} blur={2.8} far={6} frames={1}/><OrbitControls ref={controls} makeDefault minDistance={scene.camera.minDistance} maxDistance={scene.camera.maxDistance} minPolarAngle={.28} maxPolarAngle={1.76} enablePan={false} onChange={()=>invalidate()}/></>; }
