"use client";
import { ContactShadows, OrbitControls } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { useEffect, useMemo, useRef } from "react";
import { CatmullRomCurve3, MathUtils, PerspectiveCamera, Vector3 } from "three";
import type { Group } from "three";
import type { OrbitControls as OrbitControlsImpl } from "three-stdlib";
import type { Visual3DPart, Visual3DScene } from "@/lib/visual-3d";
import type { VisualCategory } from "@/lib/visual-build";

const accents = { empty: "#315543", installed: "#000000", next: "#dfb85e", warning: "#e3a83c", conflict: "#e05a48" } as const;
function Material({ part, active, color = part.profile.primaryColor, metalness = part.profile.metalness, roughness = part.profile.roughness }: { part: Visual3DPart; active: boolean; color?: string; metalness?: number; roughness?: number }) {
 const ghost = part.state === "empty" || part.state === "next"; const accent = active ? "#dfb85e" : accents[part.state];
 return <meshStandardMaterial color={color} metalness={metalness} roughness={roughness} transparent={ghost} opacity={ghost ? .2 : 1} wireframe={part.state === "empty"} emissive={accent} emissiveIntensity={active ? .28 : part.state === "installed" ? .015 : .14}/>;
}
function Interactive({ part, children, onSelect, onHover }: { part: Visual3DPart; children: React.ReactNode; onSelect: (p: Visual3DPart) => void; onHover: (p?: Visual3DPart) => void }) {
 return <group position={part.position} onClick={e=>{e.stopPropagation();onSelect(part)}} onPointerOver={e=>{e.stopPropagation();document.body.style.cursor="pointer";onHover(part)}} onPointerOut={()=>{document.body.style.cursor="";onHover()}}>{children}</group>;
}
function Fan({ part, active, radius=.32 }: {part:Visual3DPart;active:boolean;radius?:number}) { return <group><mesh rotation={[0,Math.PI/2,0]}><cylinderGeometry args={[radius,radius,.1,24]}/><Material part={part} active={active} color="#202622"/></mesh><mesh rotation={[0,Math.PI/2,0]} position={[.06,0,0]}><torusGeometry args={[radius*.67,.026,8,24]}/><meshStandardMaterial color="#87928c" metalness={.5} roughness={.45}/></mesh></group>; }
function Tubes({part,active}:{part:Visual3DPart;active:boolean}) { const paths=part.tubePaths!; const curves=useMemo(()=>paths.map(path=>new CatmullRomCurve3(path.map(point=>new Vector3(point[0]-part.position[0],point[1]-part.position[1],point[2]-part.position[2])))),[part.position,paths]); return <>{curves.map((curve,i)=><mesh key={i}><tubeGeometry args={[curve,32,.045,9,false]}/><Material part={part} active={active} color="#111714" roughness={.82}/></mesh>)}</>; }
type Vector3TupleLike=[number,number,number];
function Radiator({part,active}:{part:Visual3DPart;active:boolean}) { const [w,h,d]=part.size, vertical=part.mount!=="top", long=vertical?h:d, spacing=long/part.instances; return <group><mesh><boxGeometry args={part.size}/><Material part={part} active={active} color="#252c28"/></mesh>{Array.from({length:part.instances},(_,i)=>{const offset=(i-(part.instances-1)/2)*spacing; const position:Vector3TupleLike=part.mount==="top"?[0,-h/2-.055,offset]:part.mount==="front"?[0,offset,-d/2-.055]:[w/2+.055,offset,0]; const rotation:Vector3TupleLike=part.mount==="top"?[0,0,Math.PI/2]:part.mount==="front"?[0,Math.PI/2,0]:[0,0,0]; return <group key={i} position={position} rotation={rotation}><Fan part={part} active={active} radius={Math.min(.55,spacing*.42)}/></group>})}</group>; }
function Component({part,active}:{part:Visual3DPart;active:boolean}) {
 if(part.kind==="motherboard") { const [w,h,d]=part.size; return <group><mesh><boxGeometry args={part.size}/><Material part={part} active={active}/></mesh><mesh position={[w/2+.035,h*.25,-d*.28]}><boxGeometry args={[.06,h*.2,d*.24]}/><Material part={part} active={active} color={part.profile.secondaryColor}/></mesh></group>; }
 if(part.kind==="cpu") return <mesh><boxGeometry args={part.size}/><Material part={part} active={active} color="#d9dedb" metalness={.92} roughness={.18}/></mesh>;
 if(part.kind==="ram") return <>{Array.from({length:part.instances},(_,i)=><mesh key={i} position={[0,0,(i-(part.instances-1)/2)*.16]}><boxGeometry args={[part.size[0],part.size[1],.1]}/><Material part={part} active={active}/></mesh>)}</>;
 if(part.kind==="gpu") { const connectors=part.metadata.hpwr?1:Math.max(1,Math.min(3,Number(part.metadata.conn8||0)+Number(part.metadata.conn6||0))); const [w,h,d]=part.size; return <group><mesh><boxGeometry args={part.size}/><Material part={part} active={active}/></mesh><mesh position={[-w/2-.04,-.05,-d/2+.06]}><boxGeometry args={[.08,h*.9,.12]}/><meshStandardMaterial color="#aeb6b1" metalness={.8}/></mesh><mesh position={[w/2+.006,0,0]}><boxGeometry args={[.012,h*.5,d*.55]}/><meshStandardMaterial color={part.profile.accentColor} metalness={.55} roughness={.4}/></mesh>{Array.from({length:connectors},(_,i)=><mesh key={i} position={[0,h/2+.05,d*.28-i*.25]}><boxGeometry args={[.28,.1,.18]}/><meshStandardMaterial color="#090c0a"/></mesh>)}</group>; }
 if(part.kind==="air-cooler") return <group><mesh><boxGeometry args={[part.size[0]-.12,part.size[1],part.size[2]]}/><Material part={part} active={active} color="#59625d"/></mesh><group position={[part.size[0]/2-.04,0,0]}><Fan part={part} active={active}/></group></group>;
 if(part.kind==="aio") return <><Radiator part={part} active={active}/><Tubes part={part} active={active}/><group position={part.connectionTarget!.map((v,i)=>v-part.position[i]) as Vector3TupleLike}><mesh rotation={[0,Math.PI/2,0]}><cylinderGeometry args={[.27,.27,.18,24]}/><Material part={part} active={active}/></mesh></group></>;
 if(part.kind==="m2") return <>{Array.from({length:part.instances},(_,i)=><group key={i} position={[.1,-i*.3,i*.16]}><mesh><boxGeometry args={[.1,.22,.82]}/><Material part={part} active={active} color="#244936"/></mesh><mesh position={[.06,0,-.36]}><boxGeometry args={[.02,.2,.09]}/><meshStandardMaterial color="#dfb85e" metalness={.75}/></mesh></group>)}</>;
 if(part.kind==="psu") return <group><mesh><boxGeometry args={part.size}/><Material part={part} active={active}/></mesh><group position={[part.size[0]/2+.055,0,0]}><Fan part={part} active={active} radius={Math.min(.38,part.size[1]*.32)}/></group></group>;
 if(part.kind==="fan") return <>{Array.from({length:part.instances},(_,i)=><group key={i} position={[0,(i-(part.instances-1)/2)*.76,0]}><Fan part={part} active={active}/></group>)}</>;
 const sizes:Partial<Record<Visual3DPart["kind"],Vector3TupleLike>>={"drive-25":[.18,1.0,.72],"drive-35":[.28,1.35,1.0],expansion:[.32,.26,1.5],rgb:[.08,3.5,.08]}; return <mesh><boxGeometry args={sizes[part.kind]||[.5,.5,.5]}/><Material part={part} active={active}/></mesh>;
}
function Chassis({scene}:{scene:Visual3DScene}) { const {size}=scene.layout; const [w,h,d]=size; const t=.08; const dual=scene.layout.family==="dual-chamber", airflow=scene.layout.family==="airflow"; return <group><mesh position={[scene.layout.tray[0],0,0]}><boxGeometry args={[t,h*.91,d*.9]}/><meshStandardMaterial color="#26352d" roughness={.64}/></mesh><mesh position={[0,-h/2+t/2,0]}><boxGeometry args={[w,t,d]}/><meshStandardMaterial color="#36413c" metalness={.7}/></mesh><mesh position={[0,h/2-t/2,0]}><boxGeometry args={[w,t,d]}/><meshStandardMaterial color="#36413c" metalness={.7}/></mesh><mesh position={[0,0,-d/2+t/2]}><boxGeometry args={[w,h,t]}/><meshStandardMaterial color="#303a35" metalness={.72}/></mesh><mesh position={[0,0,d/2-t/2]}><boxGeometry args={[w,h,t]}/><meshPhysicalMaterial color={airflow?"#5a7767":"#40544a"} wireframe={airflow} transparent opacity={airflow?.32:.1} roughness={.35} transmission={airflow?0:.45}/></mesh>{dual&&<mesh position={[-w*.23,-h*.29,0]}><boxGeometry args={[w*.42,h*.32,d*.9]}/><meshStandardMaterial color="#1d2822" roughness={.5}/></mesh>}<mesh position={[w/2-t/2,0,0]}><boxGeometry args={[t,h*.94,d*.94]}/><meshPhysicalMaterial color="#7ba18d" transparent opacity={.09} roughness={.12} transmission={.55}/></mesh></group>; }
export default function ForgeScene({scene,active,onSelect,onHover,resetSignal}:{scene:Visual3DScene;active?:VisualCategory;onSelect:(p:Visual3DPart)=>void;onHover:(p?:Visual3DPart)=>void;resetSignal:number}) { const controls=useRef<OrbitControlsImpl>(null), assembly=useRef<Group>(null); const {camera,size,invalidate}=useThree(); const cameraRef=useRef(camera); const visibleParts=scene.parts.filter(part=>part.state!=="empty"); useEffect(()=>{const fitted=cameraRef.current; if(!(fitted instanceof PerspectiveCamera))return; const [w,h,d]=scene.layout.size; const radius=Math.hypot(w,h,d)/2; const vfov=MathUtils.degToRad(fitted.fov); const hfov=2*Math.atan(Math.tan(vfov/2)*fitted.aspect); const distance=radius/Math.sin(Math.min(vfov,hfov)/2)*1.03; const direction=new Vector3(1,.48,1.18).normalize(); fitted.position.copy(new Vector3(...scene.focusTarget)).addScaledVector(direction,distance); fitted.near=Math.max(.05,distance-radius*1.4); fitted.far=distance+radius*5; fitted.updateProjectionMatrix(); controls.current?.target.set(...scene.focusTarget); controls.current?.update(); invalidate()},[invalidate,resetSignal,scene,size.width,size.height]); return <><ambientLight intensity={1.5} color="#e8f2eb"/><hemisphereLight args={["#d9eee4","#294536",1.9]}/><directionalLight position={[5,7,6]} intensity={3} color="#ffe9bd"/><directionalLight position={[-4,2,5]} intensity={2.1} color="#79cbb7"/><pointLight position={[1,1,0]} intensity={2.4} distance={8} color="#a7d3bd"/><group ref={assembly}><Chassis scene={scene}/>{visibleParts.map(part=><Interactive key={part.id} part={part} onSelect={onSelect} onHover={onHover}><Component part={part} active={active===part.category}/></Interactive>)}</group><ContactShadows position={[0,scene.bounds.min[1]-.05,0]} opacity={.3} scale={8} blur={2.8} far={6} frames={1}/><OrbitControls ref={controls} makeDefault minDistance={scene.camera.minDistance} maxDistance={scene.camera.maxDistance} minPolarAngle={.42} maxPolarAngle={1.62} minAzimuthAngle={-.4} maxAzimuthAngle={2.25} enablePan={false} onChange={()=>invalidate()}/></>; }
